gcc8 - use -Wl,--no-as-needed to prevent linker failures
with:

    gcc (Debian 9.2.1-4) 9.2.1 20190821
    GNU ld (GNU Binutils for Debian) 2.32.51.20190821

errors:

    cc  -lX11 -lImlib2 -lXinerama  hsetroot.o   -o hsetroot
    /usr/bin/ld: hsetroot.o: in function `setRootAtoms':
    /home/himdel/hsetroot/hsetroot.c:76: undefined reference to `XInternAtom'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:77: undefined reference to `XInternAtom'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:91: undefined reference to `XInternAtom'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:92: undefined reference to `XInternAtom'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:98: undefined reference to `XChangeProperty'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:99: undefined reference to `XChangeProperty'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:81: undefined reference to `XGetWindowProperty'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:84: undefined reference to `XGetWindowProperty'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:87: undefined reference to `XKillClient'
    /usr/bin/ld: hsetroot.o: in function `parse_color':
    /home/himdel/hsetroot/hsetroot.c:123: undefined reference to `XParseColor'
    /usr/bin/ld: hsetroot.o: in function `load_image':
    /home/himdel/hsetroot/hsetroot.c:138: undefined reference to `imlib_load_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:143: undefined reference to `imlib_context_set_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:144: undefined reference to `imlib_image_get_width'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:145: undefined reference to `imlib_image_get_height'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:163: undefined reference to `imlib_context_set_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:214: undefined reference to `imlib_blend_image_onto_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:179: undefined reference to `imlib_blend_image_onto_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:196: undefined reference to `imlib_image_copy_rect'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:197: undefined reference to `imlib_image_copy_rect'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:219: undefined reference to `imlib_context_set_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:220: undefined reference to `imlib_free_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:222: undefined reference to `imlib_context_set_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:149: undefined reference to `imlib_image_set_has_alpha'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:150: undefined reference to `imlib_create_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:151: undefined reference to `imlib_context_set_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:154: undefined reference to `imlib_get_color_modifier_tables'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:157: undefined reference to `imlib_set_color_modifier_tables'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:159: undefined reference to `imlib_apply_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:160: undefined reference to `imlib_free_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:212: undefined reference to `imlib_blend_image_onto_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:188: undefined reference to `imlib_image_copy_rect'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:189: undefined reference to `imlib_image_copy_rect'
    /usr/bin/ld: hsetroot.o: in function `main':
    /home/himdel/hsetroot/hsetroot.c:239: undefined reference to `XOpenDisplay'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:291: undefined reference to `imlib_context_new'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:292: undefined reference to `imlib_context_push'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:294: undefined reference to `imlib_context_set_display'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:306: undefined reference to `XCreatePixmap'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:308: undefined reference to `imlib_context_set_visual'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:309: undefined reference to `imlib_context_set_colormap'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:310: undefined reference to `imlib_context_set_drawable'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:311: undefined reference to `imlib_create_color_range'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:311: undefined reference to `imlib_context_set_color_range'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:313: undefined reference to `imlib_create_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:314: undefined reference to `imlib_context_set_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:316: undefined reference to `imlib_context_set_color'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:317: undefined reference to `imlib_image_fill_rectangle'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:319: undefined reference to `imlib_context_set_dither'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:320: undefined reference to `imlib_context_set_blend'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:329: undefined reference to `imlib_create_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:330: undefined reference to `imlib_context_set_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:326: undefined reference to `imlib_apply_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:327: undefined reference to `imlib_free_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:351: undefined reference to `imlib_context_set_color'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:352: undefined reference to `imlib_image_fill_rectangle'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:564: undefined reference to `imlib_context_set_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:565: undefined reference to `imlib_apply_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:566: undefined reference to `imlib_free_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:570: undefined reference to `imlib_render_image_on_drawable'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:571: undefined reference to `imlib_free_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:572: undefined reference to `imlib_free_color_range'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:577: undefined reference to `XKillClient'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:578: undefined reference to `XSetCloseDownMode'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:580: undefined reference to `XSetWindowBackgroundPixmap'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:581: undefined reference to `XClearWindow'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:583: undefined reference to `XFlush'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:584: undefined reference to `XSync'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:586: undefined reference to `imlib_context_pop'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:587: undefined reference to `imlib_context_free'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:366: undefined reference to `imlib_context_set_color'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:367: undefined reference to `imlib_add_color_to_color_range'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:387: undefined reference to `imlib_context_set_color'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:388: undefined reference to `imlib_add_color_to_color_range'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:354: undefined reference to `imlib_free_color_range'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:355: undefined reference to `imlib_create_color_range'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:355: undefined reference to `imlib_context_set_color_range'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:399: undefined reference to `imlib_image_fill_color_range_rectangle'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:284: undefined reference to `XineramaQueryScreens'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:592: undefined reference to `XFree'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:487: undefined reference to `imlib_image_blur'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:498: undefined reference to `imlib_image_sharpen'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:468: undefined reference to `imlib_get_color_modifier_tables'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:476: undefined reference to `imlib_set_color_modifier_tables'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:509: undefined reference to `imlib_modify_color_modifier_contrast'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:520: undefined reference to `imlib_modify_color_modifier_brightness'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:531: undefined reference to `imlib_modify_color_modifier_gamma'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:543: undefined reference to `imlib_save_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:533: undefined reference to `imlib_image_flip_vertical'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:537: undefined reference to `imlib_image_flip_diagonal'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:535: undefined reference to `imlib_image_flip_horizontal'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:551: undefined reference to `imlib_free_image'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:552: undefined reference to `imlib_free_color_range'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:554: undefined reference to `imlib_context_set_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:555: undefined reference to `imlib_free_color_modifier'
    /usr/bin/ld: /home/himdel/hsetroot/hsetroot.c:558: undefined reference to `XFreePixmap'
    collect2: error: ld returned 1 exit status
    make: *** [<builtin>: hsetroot] Error 1